export interface Tool {
  id: string;
  name: string;
  description: string;
  category: 'image-gen' | 'writing' | 'video' | 'code';
  bestFor: string[];
  pricing: string;
  affiliateUrl: string;
  affiliateProgram: string;
  commissionRate: string;
  youtubeUrl?: string;
  imageUrl?: string;
  tags: string[];
}

export const tools: Tool[] = [
  // Image Generation
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: 'Text-to-image AI generator. Create stunning visuals from text prompts.',
    category: 'image-gen',
    bestFor: ['Designers', 'Marketers', 'Content Creators'],
    pricing: '$10–96/month',
    affiliateUrl: 'https://www.midjourney.com/?utm_source=hause',
    affiliateProgram: 'Midjourney Referral',
    commissionRate: '$85/signup',
    tags: ['text-to-image', 'generative-ai', 'design'],
  },
  {
    id: 'dalle3',
    name: 'DALL-E 3',
    description: 'OpenAI\'s text-to-image model. Premium quality, integrated with ChatGPT.',
    category: 'image-gen',
    bestFor: ['Professionals', 'Teams', 'API Users'],
    pricing: '$15/month (ChatGPT Plus)',
    affiliateUrl: 'https://openai.com/dall-e-3?utm_source=hause',
    affiliateProgram: 'OpenAI Creator Program',
    commissionRate: 'Variable',
    tags: ['text-to-image', 'enterprise', 'api'],
  },
  {
    id: 'firefly',
    name: 'Adobe Firefly',
    description: 'Adobe\'s generative AI tool. Integrated with Creative Cloud.',
    category: 'image-gen',
    bestFor: ['Designers', 'Creative Professionals'],
    pricing: 'Free (limited) + Creative Cloud ($55/month)',
    affiliateUrl: 'https://www.adobe.com/products/firefly?utm_source=hause',
    affiliateProgram: 'Adobe Partner Program',
    commissionRate: '5–10%',
    tags: ['text-to-image', 'adobe', 'creative-suite'],
  },
  {
    id: 'runway-gen3',
    name: 'Runway Gen-3',
    description: 'Advanced text-to-image with fine-tuning. Great for video assets.',
    category: 'image-gen',
    bestFor: ['Video Creators', 'Agencies'],
    pricing: '$12–50/month',
    affiliateUrl: 'https://runwayml.com/gen3?utm_source=hause',
    affiliateProgram: 'Runway Affiliate',
    commissionRate: '20%',
    tags: ['text-to-image', 'video-assets', 'generative'],
  },

  // Writing & Content
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'OpenAI\'s conversational AI. The most-used language model.',
    category: 'writing',
    bestFor: ['Content Creators', 'Builders', 'Professionals'],
    pricing: 'Free + $20/month (Plus)',
    affiliateUrl: 'https://chat.openai.com?utm_source=hause',
    affiliateProgram: 'OpenAI Creator Program',
    commissionRate: 'Variable',
    tags: ['language-model', 'free', 'most-popular'],
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'Advanced language model. Great for long-form content and reasoning.',
    category: 'writing',
    bestFor: ['Writers', 'Developers', 'Researchers'],
    pricing: '$20/month (Claude Pro)',
    affiliateUrl: 'https://claude.ai?utm_source=hause',
    affiliateProgram: 'Anthropic Referral',
    commissionRate: 'Custom',
    tags: ['language-model', 'reasoning', 'writing'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'Search + AI assistant. Find answers with real-time sources.',
    category: 'writing',
    bestFor: ['Researchers', 'Fact-Checkers'],
    pricing: 'Free + $20/month (Pro)',
    affiliateUrl: 'https://www.perplexity.ai?utm_source=hause',
    affiliateProgram: 'Perplexity Referral',
    commissionRate: '20–30%',
    tags: ['search', 'research', 'fact-checking'],
  },
  {
    id: 'copyai',
    name: 'Copy.ai',
    description: 'AI copywriting. Generate marketing copy, emails, social posts.',
    category: 'writing',
    bestFor: ['Marketers', 'Content Creators'],
    pricing: '$49/month',
    affiliateUrl: 'https://www.copy.ai?utm_source=hause',
    affiliateProgram: 'Copy.ai Affiliate',
    commissionRate: '25%',
    tags: ['copywriting', 'marketing', 'automation'],
  },
  {
    id: 'jasper',
    name: 'Jasper',
    description: 'Content AI for teams. Blog posts, social, emails.',
    category: 'writing',
    bestFor: ['Content Teams', 'Agencies'],
    pricing: '$39–125/month',
    affiliateUrl: 'https://www.jasper.ai?utm_source=hause',
    affiliateProgram: 'Jasper Affiliate',
    commissionRate: '30%',
    tags: ['content-creation', 'teams', 'seo'],
  },

  // Video & Audio
  {
    id: 'descript',
    name: 'Descript',
    description: 'Video editor for creators. Edit by transcription.',
    category: 'video',
    bestFor: ['Video Creators', 'Podcasters'],
    pricing: '$12–24/month',
    affiliateUrl: 'https://www.descript.com?utm_source=hause',
    affiliateProgram: 'Descript Affiliate',
    commissionRate: '20%',
    tags: ['video-editing', 'transcription', 'creators'],
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    description: 'AI video generator. Create videos with AI avatars.',
    category: 'video',
    bestFor: ['Marketers', 'Educators'],
    pricing: '$30–100/month',
    affiliateUrl: 'https://www.synthesia.io?utm_source=hause',
    affiliateProgram: 'Synthesia Affiliate',
    commissionRate: '25%',
    tags: ['ai-video', 'avatars', 'marketing'],
  },
  {
    id: 'opusclip',
    name: 'Opus Clip',
    description: 'Auto-clip long-form video for social. Perfect for YouTube creators.',
    category: 'video',
    bestFor: ['YouTube Creators', 'Podcasters'],
    pricing: '$9/month',
    affiliateUrl: 'https://www.opusclip.com?utm_source=hause',
    affiliateProgram: 'Opus Clip Affiliate',
    commissionRate: '20%',
    tags: ['youtube', 'clipping', 'shorts'],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'AI voice synthesis. Natural-sounding voiceovers.',
    category: 'video',
    bestFor: ['Creators', 'Marketers'],
    pricing: '$11–99/month',
    affiliateUrl: 'https://elevenlabs.io?utm_source=hause',
    affiliateProgram: 'ElevenLabs Affiliate',
    commissionRate: '20%',
    tags: ['voice-synthesis', 'voiceover', 'audio'],
  },
  {
    id: 'runway',
    name: 'Runway ML',
    description: 'Video generation & editing with AI. Create videos from text.',
    category: 'video',
    bestFor: ['Video Creators', 'Designers'],
    pricing: '$12–76/month',
    affiliateUrl: 'https://runwayml.com?utm_source=hause',
    affiliateProgram: 'Runway Affiliate',
    commissionRate: '20%',
    tags: ['video-generation', 'ai-editing', 'creators'],
  },

  // Code & Automation
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Connect your apps. Automate workflows without code.',
    category: 'code',
    bestFor: ['Small Business', 'Freelancers', 'Teams'],
    pricing: '$19–49/month',
    affiliateUrl: 'https://zapier.com?utm_source=hause',
    affiliateProgram: 'Zapier Affiliate',
    commissionRate: '20–30%',
    tags: ['automation', 'no-code', 'integrations'],
  },
  {
    id: 'make',
    name: 'Make',
    description: 'Automation platform. More powerful than Zapier.',
    category: 'code',
    bestFor: ['Developers', 'Agencies'],
    pricing: '$9–299/month',
    affiliateUrl: 'https://www.make.com?utm_source=hause',
    affiliateProgram: 'Make Affiliate',
    commissionRate: '25%',
    tags: ['automation', 'integrations', 'workflow'],
  },
  {
    id: 'replit',
    name: 'Replit',
    description: 'Online IDE. Build, share, deploy code instantly.',
    category: 'code',
    bestFor: ['Developers', 'Students'],
    pricing: '$7/month',
    affiliateUrl: 'https://replit.com?utm_source=hause',
    affiliateProgram: 'Replit Affiliate',
    commissionRate: '15%',
    tags: ['ide', 'coding', 'deployment'],
  },
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    description: 'AI pair programmer. Get code suggestions in your editor.',
    category: 'code',
    bestFor: ['Developers'],
    pricing: '$10/month',
    affiliateUrl: 'https://github.com/features/copilot?utm_source=hause',
    affiliateProgram: 'GitHub Partner Program',
    commissionRate: 'Variable',
    tags: ['ai-coding', 'copilot', 'development'],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'AI-first code editor. Built for AI-assisted development.',
    category: 'code',
    bestFor: ['Developers', 'AI-first teams'],
    pricing: '$20/month',
    affiliateUrl: 'https://cursor.sh?utm_source=hause',
    affiliateProgram: 'Cursor',
    commissionRate: 'TBD',
    tags: ['ide', 'ai-coding', 'development'],
  },
];

export const categories = [
  { id: 'image-gen', name: 'Image Generation', description: 'Create visuals with AI' },
  { id: 'writing', name: 'Writing & Content', description: 'Write and create content faster' },
  { id: 'video', name: 'Video & Audio', description: 'Produce video and audio with AI' },
  { id: 'code', name: 'Code & Automation', description: 'Build and automate with code' },
];

export function getToolsByCategory(category: string) {
  return tools.filter((tool) => tool.category === category);
}
