export interface Tool {
  id: string;
  name: string;
  description: string;
  category: 'image-gen' | 'writing' | 'video' | 'code';
  bestFor: string[];
  pricing: string;
  affiliateUrl: string;
  affiliateProgram: string;
  commissionRate: string;
  tags?: string[];
}

export const tools: Tool[] = [
  // Image Generation
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: 'Text-to-image AI generator. Create stunning visuals from text prompts.',
    category: 'image-gen',
    bestFor: ['Designers', 'Marketers', 'Content Creators'],
    pricing: '$10–96/month',
    affiliateUrl: 'https://www.midjourney.com/?utm_source=hause',
    affiliateProgram: 'Midjourney Referral',
    commissionRate: '$85/signup',
    tags: ['text-to-image', 'generative-ai', 'design'],
  },
  {
    id: 'dalle3',
    name: 'DALL-E 3',
    description: 'OpenAI\'s text-to-image model. Premium quality, integrated with ChatGPT.',
    category: 'image-gen',
    bestFor: ['Professionals', 'Teams', 'API Users'],
    pricing: '$15/month (ChatGPT Plus)',
    affiliateUrl: 'https://openai.com/dall-e-3?utm_source=hause',
    affiliateProgram: 'OpenAI Creator Program',
    commissionRate: 'Variable',
    tags: ['text-to-image', 'enterprise', 'api'],
  },
  {
    id: 'firefly',
    name: 'Adobe Firefly',
    description: 'Adobe\'s generative AI tool. Integrated with Creative Cloud.',
    category: 'image-gen',
    bestFor: ['Designers', 'Creative Professionals'],
    pricing: 'Free (limited) + Creative Cloud ($55/month)',
    affiliateUrl: 'https://www.adobe.com/products/firefly?utm_source=hause',
    affiliateProgram: 'Adobe Partner Program',
    commissionRate: '5–10%',
    tags: ['text-to-image', 'adobe', 'creative-suite'],
  },
  {
    id: 'runway-gen3',
    name: 'Runway Gen-3',
    description: 'Advanced text-to-image with fine-tuning. Great for video assets.',
    category: 'image-gen',
    bestFor: ['Video Creators', 'Agencies'],
    pricing: '$12–50/month',
    affiliateUrl: 'https://runwayml.com/gen3?utm_source=hause',
    affiliateProgram: 'Runway Affiliate',
    commissionRate: '20%',
    tags: ['text-to-image', 'video-assets', 'generative'],
  },

  // Writing & Content
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'OpenAI\'s conversational AI. The most-used language model.',
    category: 'writing',
    bestFor: ['Content Creators', 'Builders', 'Professionals'],
    pricing: 'Free + $20/month (Plus)',
    affiliateUrl: 'https://chat.openai.com?utm_source=hause',
    affiliateProgram: 'OpenAI Creator Program',
    commissionRate: 'Variable',
    tags: ['language-model', 'free', 'most-popular'],
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'Advanced language model. Great for long-form content and reasoning.',
    category: 'writing',
    bestFor: ['Writers', 'Developers', 'Researchers'],
    pricing: '$20/month (Claude Pro)',
    affiliateUrl: 'https://claude.ai?utm_source=hause',
    affiliateProgram: 'Anthropic Referral',
    commissionRate: 'Custom',
    tags: ['language-model', 'reasoning', 'writing'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'Search + AI assistant. Find answers with real-time sources.',
    category: 'writing',
    bestFor: ['Researchers', 'Fact-Checkers'],
    pricing: 'Free + $20/month (Pro)',
    affiliateUrl: 'https://www.perplexity.ai?utm_source=hause',
    affiliateProgram: 'Perplexity Referral',
    commissionRate: '20–30%',
    tags: ['search', 'ai-assistant', 'research'],
  },
  {
    id: 'copyai',
    name: 'Copy.ai',
    description: 'AI copywriting tool for marketing and sales. Pre-built templates.',
    category: 'writing',
    bestFor: ['Marketers', 'Copywriters', 'Sales Teams'],
    pricing: 'Free + $49/month (Pro)',
    affiliateUrl: 'https://www.copy.ai?utm_source=hause',
    affiliateProgram: 'Copy.ai Affiliate',
    commissionRate: '30%',
    tags: ['copywriting', 'marketing', 'templates'],
  },
  {
    id: 'jasperai',
    name: 'Jasper',
    description: 'Enterprise AI content platform. Built for teams and brands.',
    category: 'writing',
    bestFor: ['Content Teams', 'Marketing Agencies'],
    pricing: 'From $39/month',
    affiliateUrl: 'https://www.jasper.ai?utm_source=hause',
    affiliateProgram: 'Jasper Affiliate',
    commissionRate: '30%',
    tags: ['content', 'enterprise', 'teams'],
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    description: 'AI writing assistant. Grammar, tone, and clarity suggestions.',
    category: 'writing',
    bestFor: ['Writers', 'Professionals', 'Teams'],
    pricing: 'Free + $12/month (Premium)',
    affiliateUrl: 'https://www.grammarly.com?utm_source=hause',
    affiliateProgram: 'Grammarly Affiliate',
    commissionRate: '20%',
    tags: ['writing-assistant', 'editing', 'grammar'],
  },

  // Video & Audio
  {
    id: 'descript',
    name: 'Descript',
    description: 'Video editor that works like a document. Edit by editing text.',
    category: 'video',
    bestFor: ['Content Creators', 'Podcasters'],
    pricing: '$12–24/month',
    affiliateUrl: 'https://www.descript.com?utm_source=hause',
    affiliateProgram: 'Descript Affiliate',
    commissionRate: '20%',
    tags: ['video-editing', 'transcription', 'podcasting'],
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    description: 'AI video generation. Create videos from text with AI avatars.',
    category: 'video',
    bestFor: ['Marketing Teams', 'E-learning Creators'],
    pricing: '$30–100/month',
    affiliateUrl: 'https://www.synthesia.io?utm_source=hause',
    affiliateProgram: 'Synthesia Affiliate',
    commissionRate: '25%',
    tags: ['video-generation', 'avatars', 'e-learning'],
  },
  {
    id: 'opusclip',
    name: 'Opus Clip',
    description: 'Turn long-form video into short clips. AI-powered.',
    category: 'video',
    bestFor: ['YouTube Creators', 'TikTok Creators'],
    pricing: '$9/month',
    affiliateUrl: 'https://www.opusclip.com?utm_source=hause',
    affiliateProgram: 'Opus Clip Affiliate',
    commissionRate: '20%',
    tags: ['short-form', 'clipping', 'repurposing'],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'AI voice generation. Natural-sounding text-to-speech.',
    category: 'video',
    bestFor: ['Creators', 'Marketers', 'Developers'],
    pricing: 'Free + $11–99/month',
    affiliateUrl: 'https://elevenlabs.io?utm_source=hause',
    affiliateProgram: 'ElevenLabs Affiliate',
    commissionRate: '20%',
    tags: ['text-to-speech', 'voice', 'audio'],
  },
  {
    id: 'runway',
    name: 'Runway',
    description: 'Creative suite for video and image generation. Gen-2, Gen-3, and more.',
    category: 'video',
    bestFor: ['Video Producers', 'Agencies'],
    pricing: '$12–50/month',
    affiliateUrl: 'https://runway.com?utm_source=hause',
    affiliateProgram: 'Runway Affiliate',
    commissionRate: '20%',
    tags: ['video-generation', 'ml-tools', 'creative'],
  },
  {
    id: 'capcut',
    name: 'CapCut',
    description: 'Free video editor with AI features. Desktop and mobile.',
    category: 'video',
    bestFor: ['Creators', 'TikTok Creators'],
    pricing: 'Free',
    affiliateUrl: 'https://www.capcut.com?utm_source=hause',
    affiliateProgram: 'CapCut Referral',
    commissionRate: 'N/A',
    tags: ['video-editing', 'free', 'mobile'],
  },

  // Code & Automation
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Connect apps and automate workflows. 6000+ integrations.',
    category: 'code',
    bestFor: ['Small Business', 'Entrepreneurs'],
    pricing: '$19–49/month',
    affiliateUrl: 'https://zapier.com?utm_source=hause',
    affiliateProgram: 'Zapier Affiliate',
    commissionRate: '20–30%',
    tags: ['automation', 'integrations', 'no-code'],
  },
  {
    id: 'make',
    name: 'Make (Integromat)',
    description: 'Visual workflow automation. More powerful than Zapier.',
    category: 'code',
    bestFor: ['Developers', 'Complex Workflows'],
    pricing: '$9–299/month',
    affiliateUrl: 'https://www.make.com?utm_source=hause',
    affiliateProgram: 'Make Affiliate',
    commissionRate: '25%',
    tags: ['automation', 'workflows', 'integrations'],
  },
  {
    id: 'replit',
    name: 'Replit',
    description: 'Online IDE. Build, test, and deploy code instantly.',
    category: 'code',
    bestFor: ['Developers', 'Students'],
    pricing: '$7/month',
    affiliateUrl: 'https://replit.com?utm_source=hause',
    affiliateProgram: 'Replit Referral',
    commissionRate: '15%',
    tags: ['ide', 'coding', 'collaboration'],
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'AI code assistant powered by OpenAI. Write code faster.',
    category: 'code',
    bestFor: ['Developers', 'Engineers'],
    pricing: '$10/month or $100/year',
    affiliateUrl: 'https://github.com/features/copilot?utm_source=hause',
    affiliateProgram: 'GitHub Referral',
    commissionRate: 'N/A',
    tags: ['code-completion', 'ai-assistant', 'github'],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'IDE with AI. Code with ChatGPT and Claude built-in.',
    category: 'code',
    bestFor: ['Developers', 'Full-stack Builders'],
    pricing: 'Free + $20/month (Pro)',
    affiliateUrl: 'https://cursor.so?utm_source=hause',
    affiliateProgram: 'Cursor Referral',
    commissionRate: 'N/A',
    tags: ['ide', 'ai-coding', 'development'],
  },
];

export function getToolsByCategory(category: Tool['category']): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getTool(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id);
}
